import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ConfigProvider } from "antd";
import SearchContextProvider from "@/context/SearchContext";
// import getAllProduct from "@/firebase/allData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: "black",
          borderRadius: 5,
          colorBgContainer: "white",
          colorBgBase: "black",
          lineWidth: 2,
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <SearchContextProvider>
            <Navbar />
            {children}
          </SearchContextProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
